Step tracker
XFL-Perseids/homebymarch pull request #2
Opened 2024-09-10 13:43 UTC by xyxare

Added step tracker + the ability to save steps across sessions

### Testing step tracker:

**Walked with app open**

Result: Step tracker ticked

**Walked with app minimized**

Result: Step tracker continued ticking

**Walked with app closed**

Result: None (intended)

### Testing step saving

**Walked, closed app, and relaunched**

Result: Number of steps on relaunch is equal to number of steps upon closing

2024-09-10 14:16 UTC, ferjen approved these changes

2024-09-10 14:28 UTC, ferjen requested changes
fix counter error 
![Uploading 458397502_1244866093335629_5599251504270952701_n.jpg…]()

2024-09-10 17:29 UTC, liechee approved these changes

2024-09-11 13:22 UTC, xyxare commented
Fixed. All I had to do was rewrite the original code and remove the `stepOffset` variable

2024-09-12 06:41 UTC, ferjen approved these changes

2024-09-12 06:41 UTC, merged